server {
    listen 3000;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /healthz {
        default_type text/plain;
        return 200 "OK";
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
